spring:
  h2:
    console:
      enabled: true
      path: /h2-console # Optional, default is /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always

#logging:
#  level:
#    org.springframework: DEBUG

logging:
  level:
    root: OFF
